dist: xenial 
language: cpp
notifications:
  email: false


language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
os:
  - linux
service: xvfb
before_install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt58-xenial

install:
  - pip install python-xlib codecov coverage
  - sudo apt-get update
  - sudo apt-get install -qq qt58base; 
  - sudo apt-get -y install qt58declarative qt58tools
  - sudo apt-get install xsel
  - source /opt/qt58/bin/qt58-env.sh;
  
before_script:
  - xauth generate :99.0 . trusted
  # Clone test apps
  - git init apps
  - cd apps
  - git remote add -f origin https://github.com/pywinauto/PywinautoTestapps/
  - git config core.sparseCheckout true
  - echo "MouseTester/source" >> .git/info/sparse-checkout
  - echo "SendKeysTester/source" >> .git/info/sparse-checkout
  - git pull origin master
  # Build test apps
  - cd MouseTester/source
  - qmake
  - make
  - chmod a+x mousebuttons
  - cp mousebuttons ../
  - cd $TRAVIS_BUILD_DIR
  - cd apps/SendKeysTester/source
  - qmake
  - make
  - chmod a+x send_keys_test_app
  - cp send_keys_test_app ../
  - cd $TRAVIS_BUILD_DIR

script:
  - coverage run -a --include=pywinauto/mouse.py pywinauto/unittests/test_mouse.py
  - coverage run -a --include=pywinauto/linux/keyboard.py pywinauto/unittests/test_keyboard.py
  - coverage run -a --include=pywinauto/linux/clipboard.py pywinauto/unittests/test_clipboard_linux.py

after_success:
  - codecov
